[phases.setup]
nixPkgs = ["chromium", "nss", "freetype", "harfbuzz", "cacert"]

[phases.build]
cmds = ["npm install", "cd dashboard && npm install && npm run build"]

[start]
cmd = "node server/index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"
